# Generated by Django 2.1.7 on 2019-02-22 22:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='team',
        ),
        migrations.AddField(
            model_name='team',
            name='part_of',
            field=models.ManyToManyField(blank=True, related_name='team', to=settings.AUTH_USER_MODEL),
        ),
    ]
