# Generated by Django 2.1.7 on 2019-03-06 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_board'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='owner',
        ),
        migrations.AddField(
            model_name='team',
            name='possess',
            field=models.ManyToManyField(blank=True, related_name='team', to='core.Board'),
        ),
    ]
