# Generated by Django 2.1.7 on 2019-03-06 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190306_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='possess',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.List'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='possess',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='core.Board'),
            preserve_default=False,
        ),
    ]
