# Generated by Django 2.1.7 on 2019-03-06 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190306_1049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='possess',
        ),
        migrations.RemoveField(
            model_name='team',
            name='possess',
        ),
        migrations.AddField(
            model_name='board',
            name='belongs_to',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Team'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='list',
            name='belongs_to',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Board'),
            preserve_default=False,
        ),
    ]
