# Generated by Django 2.1.7 on 2019-03-06 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190306_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='belongs_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boards', to='core.Team'),
        ),
        migrations.AlterField(
            model_name='list',
            name='belongs_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lists', to='core.Board'),
        ),
    ]
